# Generated by Django 5.1.3 on 2024-11-19 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('std_name', models.CharField(max_length=200)),
                ('std_phone', models.CharField(max_length=20)),
                ('std_parent', models.CharField(max_length=200)),
                ('std_fuculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Student_grading.faculty')),
            ],
        ),
    ]
