# Generated by Django 5.1.3 on 2024-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_grading', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
